CREATE TABLE IF NOT EXISTS daily_order_sequences (
  sequence_date TEXT PRIMARY KEY,
  last_value INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_created_payment
ON orders(created_at, payment_status, status);

UPDATE breeds SET origin = CASE
  WHEN name IN ('布偶猫','缅因猫','矮脚猫','曼基康','孟加拉豹猫','萨凡纳猫','塞伦盖蒂猫','欧西猫','雪鞋猫','加利福尼亚闪亮猫','约克巧克力猫') THEN '美国 · 北美洲'
  WHEN name IN ('英短蓝猫','银渐层','金渐层','蓝金渐层','紫金渐层','金点','银点','乳白','德文卷毛','科尼斯卷毛','柯尼斯卷毛','东方猫','哈瓦那棕猫') THEN '英国 · 西欧'
  WHEN name IN ('暹罗猫','呵叻猫') THEN '泰国 · 东南亚'
  WHEN name IN ('波斯猫','加菲猫','喜马拉雅猫') THEN '伊朗高原及欧美育种体系'
  WHEN name IN ('折耳猫','高地猫') THEN '苏格兰 · 英国'
  WHEN name IN ('俄罗斯蓝猫','西伯利亚猫','库里尔短尾猫') THEN '俄罗斯 · 欧亚大陆北部'
  WHEN name IN ('挪威森林猫') THEN '挪威 · 北欧'
  WHEN name IN ('新加坡猫') THEN '新加坡 · 东南亚'
  WHEN name IN ('缅甸猫','伯曼猫') THEN '缅甸及法国现代育种体系'
  WHEN name IN ('日本短尾猫') THEN '日本 · 东亚'
  WHEN name IN ('中国狸花猫','狸花猫','三花猫') THEN '中国 · 东亚'
  WHEN name IN ('土耳其梵猫','安哥拉猫','土耳其安哥拉') THEN '土耳其 · 安纳托利亚'
  WHEN name IN ('夏特尔猫','卡尔特猫') THEN '法国 · 西欧'
  WHEN name IN ('曼岛猫') THEN '马恩岛 · 不列颠群岛'
  WHEN name IN ('斯芬克斯','无毛猫') THEN '加拿大 · 北美洲'
  WHEN name IN ('阿比西尼亚') THEN '埃塞俄比亚及英国育种体系'
  WHEN name IN ('塞浦路斯猫') THEN '塞浦路斯 · 东地中海'
  WHEN name IN ('西高地','苏牧','喜乐蒂','古牧') THEN '英国 · 不列颠群岛'
  WHEN name IN ('马尔济斯') THEN '马耳他 · 地中海'
  WHEN name IN ('雪纳瑞','德牧','杜宾','罗威纳') THEN '德国 · 中欧'
  WHEN name IN ('金毛') THEN '苏格兰 · 英国'
  WHEN name IN ('拉布拉多','纽芬兰犬') THEN '加拿大 · 北美洲'
  WHEN name IN ('哈士奇','阿拉斯加') THEN '西伯利亚及美国阿拉斯加'
  WHEN name IN ('柴犬','秋田') THEN '日本 · 东亚'
  WHEN name IN ('萨摩耶') THEN '西伯利亚 · 俄罗斯'
  WHEN name IN ('柯基') THEN '威尔士 · 英国'
  WHEN name IN ('边牧') THEN '英格兰与苏格兰边境'
  WHEN name IN ('贵宾','法斗','比熊') THEN '法国及西欧现代育种体系'
  WHEN name IN ('巴哥','京巴','西施','松狮','藏獒','冠毛犬') THEN '中国 · 东亚'
  WHEN name IN ('博美') THEN '德国波美拉尼亚地区'
  WHEN name IN ('伯恩山') THEN '瑞士 · 中欧'
  WHEN name IN ('圣伯纳') THEN '瑞士与意大利阿尔卑斯山区'
  WHEN name IN ('斑点狗') THEN '克罗地亚 · 达尔马提亚'
  WHEN name IN ('大丹犬') THEN '德国 · 中欧'
  WHEN name IN ('灵缇') THEN '古埃及及英国现代育种体系'
  WHEN name IN ('惠比特','牛头梗','约克夏') THEN '英国 · 西欧'
  WHEN name IN ('吉娃娃') THEN '墨西哥 · 北美洲'
  WHEN name IN ('腊肠') THEN '德国 · 中欧'
  WHEN name IN ('虎皮鹦鹉') THEN '澳大利亚 · 大洋洲'
  WHEN name IN ('玄凤鹦鹉') THEN '澳大利亚内陆地区'
  WHEN name IN ('牡丹鹦鹉') THEN '非洲东部及南部'
  WHEN name IN ('小太阳鹦鹉') THEN '南美洲东北部'
  WHEN name IN ('金丝雀') THEN '西班牙加那利群岛'
  WHEN name IN ('文鸟','珍珠鸟') THEN '澳大利亚及东南亚'
  WHEN name IN ('锦鲤','金鱼') THEN '中国起源、日本体系化培育'
  WHEN name IN ('龙鱼','银龙') THEN '东南亚及南美洲热带流域'
  WHEN name IN ('孔雀鱼','红剑','玛丽','黑玛丽') THEN '中美洲及南美洲北部'
  WHEN name IN ('神仙鱼','七彩神仙','地图鱼','红绿灯') THEN '南美洲亚马孙流域'
  WHEN name IN ('斗鱼') THEN '泰国及湄公河流域'
  WHEN name IN ('小丑鱼','蓝魔','倒吊','蝴蝶鱼','海马') THEN '印度洋—太平洋珊瑚礁海域'
  WHEN name IN ('垂耳兔','侏儒兔','荷兰猪') THEN '欧洲现代育种体系'
  WHEN name IN ('龙猫') THEN '南美洲安第斯山脉'
  WHEN name IN ('蜜袋鼯') THEN '澳大利亚及新几内亚'
  WHEN name IN ('仓鼠') THEN '叙利亚及中亚地区'
  WHEN name IN ('刺猬') THEN '非洲及欧洲驯养体系'
  WHEN name IN ('守宫','鬃狮蜥') THEN '澳大利亚及亚洲热带地区'
  WHEN name IN ('玉米蛇') THEN '美国东南部'
  WHEN name IN ('角蛙') THEN '南美洲温带草原地区'
  WHEN name IN ('羊驼') THEN '南美洲安第斯高原'
  WHEN name IN ('鸵鸟') THEN '非洲草原地区'
  WHEN name IN ('人工孔雀') THEN '印度次大陆起源、人工繁育'
  WHEN category_id = 1 THEN '世界猫种育种档案 · 品种登记地可追溯'
  WHEN category_id = 2 THEN '世界犬种育种档案 · 品种登记地可追溯'
  WHEN category_id = 3 THEN '世界鸟类原生分布与人工繁育档案'
  WHEN category_id = 4 THEN '全球淡水或海洋原生水域档案'
  WHEN category_id = 5 THEN '物种原生分布与合规人工繁育档案'
  ELSE '中国及全球合规人工繁育体系'
END;
