import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import './ServiceApp.css'

const API_BASE=import.meta.env.PROD?'':import.meta.env.VITE_API_BASE||'http://127.0.0.1:3001'
const TOKEN_KEY='fuchong-service-agent-token'
const AGENT_KEY='fuchong-service-agent'
type Group={group_key:string;label:string;description:string;active_count:number;waiting_count:number;unread_count:number}
type Session={id:number;customer_code:string;nickname:string;phone?:string;status:'ai'|'human_pending'|'human';service_type:string;group_key:string;latest_message:string;latest_message_at:string;unread_count:number;assigned_to?:string;handoff_reason?:string}
type Message={id:number;sender:'user'|'service'|'agent';content:string;created_at:string}
const marks:Record<string,string>={purchase:'购',order:'单',after_sale:'售',pet_health:'护',logistics:'运',official:'综'}
const replyLabels:Record<string,string>={purchase:'购买咨询回复',order:'订单咨询回复',after_sale:'售后服务回复',pet_health:'健康咨询回复',logistics:'物流帮助回复',official:'官方客服回复'}
const statusName:Record<string,string>={ai:'自动接待',human_pending:'待人工处理',human:'人工接待中'}
const quickReplies=['您好，我是客服经理，正在为您核实。','收到，我已经看到您的问题，请稍等片刻。','为了准确处理，请补充订单号或商品名称。']

export default function ServiceApp(){
  const [token,setToken]=useState(()=>localStorage.getItem(TOKEN_KEY)||sessionStorage.getItem('fuchong-feishu-agent-token')||'')
  const [agent,setAgent]=useState<{open_id:string;name:string}|null>(()=>{try{return JSON.parse(localStorage.getItem(AGENT_KEY)||sessionStorage.getItem('fuchong-feishu-agent')||'null')}catch{return null}})
  const [groups,setGroups]=useState<Group[]>([]),[groupKey,setGroupKey]=useState('purchase')
  const [sessions,setSessions]=useState<Session[]>([]),[active,setActive]=useState<Session|null>(null),[messages,setMessages]=useState<Message[]>([])
  const [reply,setReply]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[online,setOnline]=useState(true)
  const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[loggingIn,setLoggingIn]=useState(false),[pushEnabled,setPushEnabled]=useState(false),[pushReady,setPushReady]=useState(false)
  const [lastSync,setLastSync]=useState<Date|null>(null)
  const chatEnd=useRef<HTMLDivElement>(null)
  const pushedSessionLoaded=useRef(false)
  const headers=useMemo<Record<string,string>>(()=>{const value:Record<string,string>={'content-type':'application/json'};if(token)value.Authorization=`Feishu ${token}`;return value},[token])
  const api=useCallback(async(path:string,init:RequestInit={})=>{const response=await fetch(`${API_BASE}${path}`,{...init,headers:{...headers,...(init.headers||{})}});const data=await response.json().catch(()=>({error:'服务暂时不可用'}));if(response.status===401){localStorage.removeItem(TOKEN_KEY);setToken('')}if(!response.ok)throw new Error(data.error||data.message||'操作失败');return data},[headers])

  const saveIdentity=(data:{token:string;agent:{open_id:string;name:string}})=>{localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(AGENT_KEY,JSON.stringify(data.agent));setToken(data.token);setAgent(data.agent)}
  const exchangeAdmin=useCallback(async(adminToken:string)=>{const response=await fetch(`${API_BASE}/api/feishu-service/admin-auth`,{method:'POST',headers:{Authorization:`Bearer ${adminToken}`}});const data=await response.json();if(!response.ok)throw new Error(data.error||data.message||'客服身份验证失败');saveIdentity(data)},[])
  useEffect(()=>{if(token){localStorage.setItem(TOKEN_KEY,token);return}const adminToken=localStorage.getItem('fuchong-admin-token');if(adminToken)void exchangeAdmin(adminToken).catch(()=>{})},[token,exchangeAdmin])

  const login=async(event:FormEvent)=>{event.preventDefault();setLoggingIn(true);setError('');try{const response=await fetch(`${API_BASE}/api/admin/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})});const data=await response.json();if(!response.ok)throw new Error(data.message||'账号或密码错误');localStorage.setItem('fuchong-admin-token',data.token);await exchangeAdmin(data.token);setPassword('')}catch(cause){setError(cause instanceof Error?cause.message:'登录失败')}finally{setLoggingIn(false)}}

  const loadQueues=useCallback(async()=>{if(!token)return;try{const [nextGroups,nextSessions]=await Promise.all([api('/api/feishu-service/groups'),api(`/api/feishu-service/sessions?group_key=${encodeURIComponent(groupKey)}`)]);setGroups(nextGroups);setSessions(nextSessions);setActive(current=>current?nextSessions.find((item:Session)=>item.id===current.id)||current:null);setOnline(true);setLastSync(new Date())}catch(cause){setOnline(false);setError(cause instanceof Error?cause.message:'会话连接失败')}},[api,groupKey,token])
  const loadMessages=useCallback(async(id:number)=>{try{setMessages(await api(`/api/feishu-service/sessions/${id}/messages`));setSessions(items=>items.map(item=>item.id===id?{...item,unread_count:0}:item))}catch(cause){setError(cause instanceof Error?cause.message:'消息加载失败')}},[api])
  useEffect(()=>{void loadQueues();const timer=window.setInterval(()=>void loadQueues(),1500);return()=>window.clearInterval(timer)},[loadQueues])
  useEffect(()=>{const id=Number(new URLSearchParams(location.search).get('session')||0);if(!token||!id||pushedSessionLoaded.current)return;pushedSessionLoaded.current=true;void api(`/api/feishu-service/sessions?session_id=${id}`).then((items:Session[])=>{const session=items[0];if(session){setGroupKey(session.group_key);setActive(session);void loadMessages(session.id)}}).catch(()=>{})},[api,loadMessages,token])
  useEffect(()=>{if(!active?.id)return;void loadMessages(active.id);const timer=window.setInterval(()=>void loadMessages(active.id),1200);return()=>window.clearInterval(timer)},[active?.id,loadMessages])
  useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth'})},[messages.length,sending])
  useEffect(()=>{const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='/service.webmanifest';document.head.appendChild(manifest);if('serviceWorker'in navigator){void navigator.serviceWorker.register('/service-sw.js',{scope:'/service'}).then(()=>setPushEnabled(Notification.permission==='granted'));navigator.serviceWorker.addEventListener('message',()=>void loadQueues())}void fetch(`${API_BASE}/api/service-app/config`).then(r=>r.json()).then(d=>setPushReady(Boolean(d.push_enabled))).catch(()=>{});return()=>manifest.remove()},[loadQueues])

  const openSession=(session:Session)=>{setActive(session);setMessages([]);void loadMessages(session.id)}
  const send=async(event:FormEvent)=>{event.preventDefault();const content=reply.trim();if(!active||!content||sending)return;setSending(true);setReply('');setMessages(items=>[...items,{id:-Date.now(),sender:'agent',content,created_at:new Date().toISOString()}]);try{await api(`/api/feishu-service/sessions/${active.id}/messages`,{method:'POST',body:JSON.stringify({content})});await Promise.all([loadMessages(active.id),loadQueues()])}catch(cause){setReply(content);setError(cause instanceof Error?cause.message:'发送失败')}finally{setSending(false)}}
  const closeSession=async()=>{if(!active)return;try{await api(`/api/feishu-service/sessions/${active.id}/close`,{method:'POST',body:'{}'});await Promise.all([loadMessages(active.id),loadQueues()])}catch(cause){setError(cause instanceof Error?cause.message:'结束失败')}}
  const subscribe=async()=>{if(!pushReady){setError('服务器消息提醒正在配置');return}if(!('serviceWorker'in navigator)||!('PushManager'in window)){setError('请先将客服工作台添加到手机桌面后再开启提醒');return}try{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('需要允许系统通知权限');const config=await api('/api/service-app/config');const ready=await navigator.serviceWorker.ready;let sub=await ready.pushManager.getSubscription();if(!sub){const raw=String(config.vapid_public_key).replace(/-/g,'+').replace(/_/g,'/'),pad='='.repeat((4-raw.length%4)%4),bytes=Uint8Array.from(atob(raw+pad),c=>c.charCodeAt(0));sub=await ready.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes})}await api('/api/service-app/push/subscribe',{method:'POST',body:JSON.stringify(sub.toJSON())});setPushEnabled(true);await api('/api/service-app/push/test',{method:'POST',body:'{}'})}catch(cause){setError(cause instanceof Error?cause.message:'提醒开启失败')}}
  const logout=()=>{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(AGENT_KEY);setToken('');setAgent(null)}
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?sessions.filter(item=>[item.nickname,item.customer_code,item.latest_message].some(v=>String(v||'').toLowerCase().includes(q))):sessions},[search,sessions])
  const unreadTotal=groups.reduce((sum,item)=>sum+Number(item.unread_count||0),0)

  if(!token)return <main className="agent-login"><form onSubmit={login}><img src="/assets/fuchong-logo.webp"/><span>移动客服工作台</span><h1>登录后回复网站顾客</h1><p>顾客消息、自动分流、人工接管与飞书共用同一套会话。</p><label>管理员账号<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>登录密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<em>{error}</em>}<button disabled={loggingIn||!password}>{loggingIn?'正在登录':'进入客服工作台'}</button></form></main>

  return <main className={`agent-shell ${active?'chat-open':''}`}>
    <header className="agent-header"><div><img src="/assets/fuchong-logo.webp"/><span><b>福宠客服 · {agent?.name||'客服经理'}</b><small><i className={online?'':'off'}/>{online?'实时连接':'正在重连'}</small></span></div><aside><button onClick={()=>void subscribe()} className={pushEnabled?'push-on':''}>{pushEnabled?'提醒已开':'开启提醒'}</button><button onClick={logout}>退出</button></aside></header>
    <nav className="agent-groups">{groups.map(group=><button key={group.group_key} data-group={group.group_key} className={groupKey===group.group_key?'active':''} onClick={()=>{setGroupKey(group.group_key);setActive(null)}}><i>{marks[group.group_key]||'客'}</i><span>{replyLabels[group.group_key]||`${group.label}回复`}</span>{group.unread_count>0&&<em>{group.unread_count>99?'99+':group.unread_count}</em>}</button>)}</nav>
    <section className="agent-queue"><header><div><small>当前分类</small><h1>{groups.find(g=>g.group_key===groupKey)?.label||'客服会话'}</h1></div><span><b>{unreadTotal}</b> 条未读</span></header><label className="agent-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索访客、会话编号或消息"/></label><div className="agent-session-list">{visible.length?visible.map(session=><button key={session.id} className={active?.id===session.id?'active':''} onClick={()=>openSession(session)}><i>{(session.nickname||'客').slice(0,1)}</i><span><strong>{session.nickname||'网站访客'}<small>{session.customer_code}</small></strong><p>{session.latest_message||'等待顾客消息'}</p><em className={session.status}>{statusName[session.status]}</em></span><time>{session.unread_count>0&&<b>{session.unread_count}</b>}{session.latest_message_at?.slice(11,16)}</time></button>):<div className="agent-empty"><b>当前分类暂无会话</b><span>新消息会实时出现在这里</span></div>}</div><footer>{lastSync?`刚刚同步 ${lastSync.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'正在连接会话'}</footer></section>
    <section className="agent-chat">{active?<><header><button className="agent-back" onClick={()=>setActive(null)}>‹</button><i>{(active.nickname||'客').slice(0,1)}</i><div><h2>{active.nickname||'网站访客'}</h2><p>{active.customer_code} · {active.service_type} · {statusName[active.status]}</p></div>{active.status!=='ai'&&<button className="agent-close" onClick={()=>void closeSession()}>切回在线客服</button>}</header>{active.handoff_reason&&<div className="agent-risk"><b>需关注</b><span>{active.handoff_reason}</span></div>}<div className="agent-messages">{messages.map(message=><article key={message.id} className={message.sender}><i>{message.sender==='user'?'客':message.sender==='agent'?'我':'福'}</i><div><small>{message.sender==='user'?'网站顾客':message.sender==='agent'?'人工客服':'自动回复'}</small><p>{message.content}</p><time>{message.created_at?.slice(11,16)}</time></div></article>)}{sending&&<div className="agent-typing"><i/><i/><i/>正在发送</div>}<div ref={chatEnd}/></div><div className="agent-composer"><div>{quickReplies.map(item=><button key={item} onClick={()=>setReply(item)}>{item}</button>)}</div><form onSubmit={send}><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={2} placeholder="输入回复，发送后立即同步到顾客网站窗口"/><button disabled={!reply.trim()||sending}>{sending?'发送中':'回复顾客'}</button></form></div></>:<div className="agent-chat-empty"><i>聊</i><h2>选择一位顾客开始回复</h2><p>每位顾客拥有独立会话，消息和接管状态实时同步。</p></div>}</section>
    {error&&<button className="agent-toast" onClick={()=>setError('')}>{error}　×</button>}
  </main>
}
